export type WorldRegion = 'Asia' | 'Europe' | 'Africa' | 'Americas' | 'Oceania' | 'Middle East'

export type WorldCountry = {
  id: string
  numericId: number
  nameEn: string
  nameAr: string
  flag: string
  region: WorldRegion
  capitalEn: string
  capitalAr: string
  iso2: string
}

export const REGION_LABELS: Record<WorldRegion, { en: string; ar: string }> = {
  Asia: { en: 'Asia', ar: 'آسيا' },
  Europe: { en: 'Europe', ar: 'أوروبا' },
  Africa: { en: 'Africa', ar: 'أفريقيا' },
  Americas: { en: 'Americas', ar: 'الأمريكتان' },
  Oceania: { en: 'Oceania', ar: 'أوقيانوسيا' },
  'Middle East': { en: 'Middle East', ar: 'الشرق الأوسط' },
}

export const WORLD_COUNTRIES: WorldCountry[] = [
  {
    id: "korea",
    numericId: 1,
    nameEn: "Republic of Korea",
    nameAr: "جمهورية كوريا الجنوبية",
    flag: "🇰🇷",
    region: "Asia",
    capitalEn: "Seoul",
    capitalAr: "سيول",
    iso2: "kr",
  },
  {
    id: "afghanistan",
    numericId: 2,
    nameEn: "Afghanistan",
    nameAr: "أفغانستان",
    flag: "🇦🇫",
    region: "Asia",
    capitalEn: "Kabul",
    capitalAr: "كابل",
    iso2: "af",
  },
  {
    id: "albania",
    numericId: 3,
    nameEn: "Albania",
    nameAr: "ألبانيا",
    flag: "🇦🇱",
    region: "Europe",
    capitalEn: "Tirana",
    capitalAr: "تيرانا",
    iso2: "al",
  },
  {
    id: "algeria",
    numericId: 4,
    nameEn: "Algeria",
    nameAr: "الجزائر",
    flag: "🇩🇿",
    region: "Africa",
    capitalEn: "Algiers",
    capitalAr: "الجزائر",
    iso2: "dz",
  },
  {
    id: "andorra",
    numericId: 5,
    nameEn: "Andorra",
    nameAr: "أندورا",
    flag: "🇦🇩",
    region: "Europe",
    capitalEn: "Andorra la Vella",
    capitalAr: "أندورا لا فيلا",
    iso2: "ad",
  },
  {
    id: "angola",
    numericId: 6,
    nameEn: "Angola",
    nameAr: "أنغولا",
    flag: "🇦🇴",
    region: "Africa",
    capitalEn: "Luanda",
    capitalAr: "لواندا",
    iso2: "ao",
  },
  {
    id: "antigua-and-barbuda",
    numericId: 7,
    nameEn: "Antigua and Barbuda",
    nameAr: "أنتيغوا وبربودا",
    flag: "🇦🇬",
    region: "Americas",
    capitalEn: "Saint John's",
    capitalAr: "سانت جونز",
    iso2: "ag",
  },
  {
    id: "argentina",
    numericId: 8,
    nameEn: "Argentina",
    nameAr: "الأرجنتين",
    flag: "🇦🇷",
    region: "Americas",
    capitalEn: "Buenos Aires",
    capitalAr: "بوينس آيرس",
    iso2: "ar",
  },
  {
    id: "armenia",
    numericId: 9,
    nameEn: "Armenia",
    nameAr: "أرمينيا",
    flag: "🇦🇲",
    region: "Asia",
    capitalEn: "Yerevan",
    capitalAr: "يريفان",
    iso2: "am",
  },
  {
    id: "australia",
    numericId: 10,
    nameEn: "Australia",
    nameAr: "أستراليا",
    flag: "🇦🇺",
    region: "Oceania",
    capitalEn: "Canberra",
    capitalAr: "كانبرا",
    iso2: "au",
  },
  {
    id: "austria",
    numericId: 11,
    nameEn: "Austria",
    nameAr: "النمسا",
    flag: "🇦🇹",
    region: "Europe",
    capitalEn: "Vienna",
    capitalAr: "فيينا",
    iso2: "at",
  },
  {
    id: "azerbaijan",
    numericId: 12,
    nameEn: "Azerbaijan",
    nameAr: "أذربيجان",
    flag: "🇦🇿",
    region: "Asia",
    capitalEn: "Baku",
    capitalAr: "باكو",
    iso2: "az",
  },
  {
    id: "bahamas",
    numericId: 13,
    nameEn: "Bahamas",
    nameAr: "جزر البهاما",
    flag: "🇧🇸",
    region: "Americas",
    capitalEn: "Nassau",
    capitalAr: "ناساو",
    iso2: "bs",
  },
  {
    id: "bahrain",
    numericId: 14,
    nameEn: "Bahrain",
    nameAr: "البحرين",
    flag: "🇧🇭",
    region: "Middle East",
    capitalEn: "Manama",
    capitalAr: "المنامة",
    iso2: "bh",
  },
  {
    id: "bangladesh",
    numericId: 15,
    nameEn: "Bangladesh",
    nameAr: "بنغلاديش",
    flag: "🇧🇩",
    region: "Asia",
    capitalEn: "Dhaka",
    capitalAr: "دكا",
    iso2: "bd",
  },
  {
    id: "barbados",
    numericId: 16,
    nameEn: "Barbados",
    nameAr: "بربادوس",
    flag: "🇧🇧",
    region: "Americas",
    capitalEn: "Bridgetown",
    capitalAr: "بريدجتاون",
    iso2: "bb",
  },
  {
    id: "belarus",
    numericId: 17,
    nameEn: "Belarus",
    nameAr: "بيلاروس",
    flag: "🇧🇾",
    region: "Europe",
    capitalEn: "Minsk",
    capitalAr: "مينسك",
    iso2: "by",
  },
  {
    id: "belgium",
    numericId: 18,
    nameEn: "Belgium",
    nameAr: "بلجيكا",
    flag: "🇧🇪",
    region: "Europe",
    capitalEn: "Brussels",
    capitalAr: "بروكسل",
    iso2: "be",
  },
  {
    id: "belize",
    numericId: 19,
    nameEn: "Belize",
    nameAr: "بليز",
    flag: "🇧🇿",
    region: "Americas",
    capitalEn: "Belmopan",
    capitalAr: "بلموبان",
    iso2: "bz",
  },
  {
    id: "benin",
    numericId: 20,
    nameEn: "Benin",
    nameAr: "بنين",
    flag: "🇧🇯",
    region: "Africa",
    capitalEn: "Porto-Novo",
    capitalAr: "بورتو نوفو",
    iso2: "bj",
  },
  {
    id: "bhutan",
    numericId: 21,
    nameEn: "Bhutan",
    nameAr: "بوتان",
    flag: "🇧🇹",
    region: "Asia",
    capitalEn: "Thimphu",
    capitalAr: "تيمفو",
    iso2: "bt",
  },
  {
    id: "bolivia",
    numericId: 22,
    nameEn: "Bolivia",
    nameAr: "بوليفيا",
    flag: "🇧🇴",
    region: "Americas",
    capitalEn: "Sucre",
    capitalAr: "سوكري",
    iso2: "bo",
  },
  {
    id: "bosnia-and-herzegovina",
    numericId: 23,
    nameEn: "Bosnia and Herzegovina",
    nameAr: "البوسنة والهرسك",
    flag: "🇧🇦",
    region: "Europe",
    capitalEn: "Sarajevo",
    capitalAr: "سراييفو",
    iso2: "ba",
  },
  {
    id: "botswana",
    numericId: 24,
    nameEn: "Botswana",
    nameAr: "بوتسوانا",
    flag: "🇧🇼",
    region: "Africa",
    capitalEn: "Gaborone",
    capitalAr: "غابورون",
    iso2: "bw",
  },
  {
    id: "brazil",
    numericId: 25,
    nameEn: "Brazil",
    nameAr: "البرازيل",
    flag: "🇧🇷",
    region: "Americas",
    capitalEn: "Brasília",
    capitalAr: "برازيليا",
    iso2: "br",
  },
  {
    id: "brunei",
    numericId: 26,
    nameEn: "Brunei",
    nameAr: "بروناي",
    flag: "🇧🇳",
    region: "Asia",
    capitalEn: "Bandar Seri Begawan",
    capitalAr: "بندر سري بكاوان",
    iso2: "bn",
  },
  {
    id: "bulgaria",
    numericId: 27,
    nameEn: "Bulgaria",
    nameAr: "بلغاريا",
    flag: "🇧🇬",
    region: "Europe",
    capitalEn: "Sofia",
    capitalAr: "صوفيا",
    iso2: "bg",
  },
  {
    id: "burkina-faso",
    numericId: 28,
    nameEn: "Burkina Faso",
    nameAr: "بوركينا فاسو",
    flag: "🇧🇫",
    region: "Africa",
    capitalEn: "Ouagadougou",
    capitalAr: "واغادوغو",
    iso2: "bf",
  },
  {
    id: "burundi",
    numericId: 29,
    nameEn: "Burundi",
    nameAr: "بوروندي",
    flag: "🇧🇮",
    region: "Africa",
    capitalEn: "Gitega",
    capitalAr: "غيتيغا",
    iso2: "bi",
  },
  {
    id: "cabo-verde",
    numericId: 30,
    nameEn: "Cabo Verde",
    nameAr: "الرأس الأخضر",
    flag: "🇨🇻",
    region: "Africa",
    capitalEn: "Praia",
    capitalAr: "برايا",
    iso2: "cv",
  },
  {
    id: "cambodia",
    numericId: 31,
    nameEn: "Cambodia",
    nameAr: "كمبوديا",
    flag: "🇰🇭",
    region: "Asia",
    capitalEn: "Phnom Penh",
    capitalAr: "بنوم بنه",
    iso2: "kh",
  },
  {
    id: "cameroon",
    numericId: 32,
    nameEn: "Cameroon",
    nameAr: "الكاميرون",
    flag: "🇨🇲",
    region: "Africa",
    capitalEn: "Yaoundé",
    capitalAr: "ياوندي",
    iso2: "cm",
  },
  {
    id: "canada",
    numericId: 33,
    nameEn: "Canada",
    nameAr: "كندا",
    flag: "🇨🇦",
    region: "Americas",
    capitalEn: "Ottawa",
    capitalAr: "أوتاوا",
    iso2: "ca",
  },
  {
    id: "central-african-republic",
    numericId: 34,
    nameEn: "Central African Republic",
    nameAr: "جمهورية أفريقيا الوسطى",
    flag: "🇨🇫",
    region: "Africa",
    capitalEn: "Bangui",
    capitalAr: "بانغي",
    iso2: "cf",
  },
  {
    id: "chad",
    numericId: 35,
    nameEn: "Chad",
    nameAr: "تشاد",
    flag: "🇹🇩",
    region: "Africa",
    capitalEn: "N'Djamena",
    capitalAr: "نجامينا",
    iso2: "td",
  },
  {
    id: "chile",
    numericId: 36,
    nameEn: "Chile",
    nameAr: "تشيلي",
    flag: "🇨🇱",
    region: "Americas",
    capitalEn: "Santiago",
    capitalAr: "سانتياغو",
    iso2: "cl",
  },
  {
    id: "china",
    numericId: 37,
    nameEn: "China",
    nameAr: "الصين",
    flag: "🇨🇳",
    region: "Asia",
    capitalEn: "Beijing",
    capitalAr: "بكين",
    iso2: "cn",
  },
  {
    id: "colombia",
    numericId: 38,
    nameEn: "Colombia",
    nameAr: "كولومبيا",
    flag: "🇨🇴",
    region: "Americas",
    capitalEn: "Bogotá",
    capitalAr: "بوغوتا",
    iso2: "co",
  },
  {
    id: "comoros",
    numericId: 39,
    nameEn: "Comoros",
    nameAr: "جزر القمر",
    flag: "🇰🇲",
    region: "Africa",
    capitalEn: "Moroni",
    capitalAr: "موروني",
    iso2: "km",
  },
  {
    id: "congo",
    numericId: 40,
    nameEn: "Congo",
    nameAr: "الكونغو",
    flag: "🇨🇬",
    region: "Africa",
    capitalEn: "Brazzaville",
    capitalAr: "برازافيل",
    iso2: "cg",
  },
  {
    id: "democratic-republic-of-congo",
    numericId: 41,
    nameEn: "Democratic Republic of the Congo",
    nameAr: "جمهورية الكونغو الديمقراطية",
    flag: "🇨🇩",
    region: "Africa",
    capitalEn: "Kinshasa",
    capitalAr: "كينشاسا",
    iso2: "cd",
  },
  {
    id: "costa-rica",
    numericId: 42,
    nameEn: "Costa Rica",
    nameAr: "كوستاريكا",
    flag: "🇨🇷",
    region: "Americas",
    capitalEn: "San José",
    capitalAr: "سان خوسيه",
    iso2: "cr",
  },
  {
    id: "cote-divoire",
    numericId: 43,
    nameEn: "Côte d'Ivoire",
    nameAr: "ساحل العاج",
    flag: "🇨🇮",
    region: "Africa",
    capitalEn: "Yamoussoukro",
    capitalAr: "ياموسوكرو",
    iso2: "ci",
  },
  {
    id: "croatia",
    numericId: 44,
    nameEn: "Croatia",
    nameAr: "كرواتيا",
    flag: "🇭🇷",
    region: "Europe",
    capitalEn: "Zagreb",
    capitalAr: "زغرب",
    iso2: "hr",
  },
  {
    id: "cuba",
    numericId: 45,
    nameEn: "Cuba",
    nameAr: "كوبا",
    flag: "🇨🇺",
    region: "Americas",
    capitalEn: "Havana",
    capitalAr: "هافانا",
    iso2: "cu",
  },
  {
    id: "cyprus",
    numericId: 46,
    nameEn: "Cyprus",
    nameAr: "قبرص",
    flag: "🇨🇾",
    region: "Europe",
    capitalEn: "Nicosia",
    capitalAr: "نيقوسيا",
    iso2: "cy",
  },
  {
    id: "czechia",
    numericId: 47,
    nameEn: "Czechia",
    nameAr: "التشيك",
    flag: "🇨🇿",
    region: "Europe",
    capitalEn: "Prague",
    capitalAr: "براغ",
    iso2: "cz",
  },
  {
    id: "denmark",
    numericId: 48,
    nameEn: "Denmark",
    nameAr: "الدنمارك",
    flag: "🇩🇰",
    region: "Europe",
    capitalEn: "Copenhagen",
    capitalAr: "كوبنهاغن",
    iso2: "dk",
  },
  {
    id: "djibouti",
    numericId: 49,
    nameEn: "Djibouti",
    nameAr: "جيبوتي",
    flag: "🇩🇯",
    region: "Africa",
    capitalEn: "Djibouti",
    capitalAr: "جيبوتي",
    iso2: "dj",
  },
  {
    id: "dominica",
    numericId: 50,
    nameEn: "Dominica",
    nameAr: "دومينيكا",
    flag: "🇩🇲",
    region: "Americas",
    capitalEn: "Roseau",
    capitalAr: "روزو",
    iso2: "dm",
  },
  {
    id: "dominican-republic",
    numericId: 51,
    nameEn: "Dominican Republic",
    nameAr: "جمهورية الدومينيكان",
    flag: "🇩🇴",
    region: "Americas",
    capitalEn: "Santo Domingo",
    capitalAr: "سانتو دومينغو",
    iso2: "do",
  },
  {
    id: "ecuador",
    numericId: 52,
    nameEn: "Ecuador",
    nameAr: "الإكوادور",
    flag: "🇪🇨",
    region: "Americas",
    capitalEn: "Quito",
    capitalAr: "كيتو",
    iso2: "ec",
  },
  {
    id: "egypt",
    numericId: 53,
    nameEn: "Egypt",
    nameAr: "مصر",
    flag: "🇪🇬",
    region: "Middle East",
    capitalEn: "Cairo",
    capitalAr: "القاهرة",
    iso2: "eg",
  },
  {
    id: "el-salvador",
    numericId: 54,
    nameEn: "El Salvador",
    nameAr: "السلفادور",
    flag: "🇸🇻",
    region: "Americas",
    capitalEn: "San Salvador",
    capitalAr: "سان سلفادور",
    iso2: "sv",
  },
  {
    id: "equatorial-guinea",
    numericId: 55,
    nameEn: "Equatorial Guinea",
    nameAr: "غينيا الاستوائية",
    flag: "🇬🇶",
    region: "Africa",
    capitalEn: "Malabo",
    capitalAr: "مالابو",
    iso2: "gq",
  },
  {
    id: "eritrea",
    numericId: 56,
    nameEn: "Eritrea",
    nameAr: "إريتريا",
    flag: "🇪🇷",
    region: "Africa",
    capitalEn: "Asmara",
    capitalAr: "أسمرة",
    iso2: "er",
  },
  {
    id: "estonia",
    numericId: 57,
    nameEn: "Estonia",
    nameAr: "إستونيا",
    flag: "🇪🇪",
    region: "Europe",
    capitalEn: "Tallinn",
    capitalAr: "تالين",
    iso2: "ee",
  },
  {
    id: "eswatini",
    numericId: 58,
    nameEn: "Eswatini",
    nameAr: "إسواتيني",
    flag: "🇸🇿",
    region: "Africa",
    capitalEn: "Mbabane",
    capitalAr: "مبابان",
    iso2: "sz",
  },
  {
    id: "ethiopia",
    numericId: 59,
    nameEn: "Ethiopia",
    nameAr: "إثيوبيا",
    flag: "🇪🇹",
    region: "Africa",
    capitalEn: "Addis Ababa",
    capitalAr: "أديس أبابا",
    iso2: "et",
  },
  {
    id: "fiji",
    numericId: 60,
    nameEn: "Fiji",
    nameAr: "فيجي",
    flag: "🇫🇯",
    region: "Oceania",
    capitalEn: "Suva",
    capitalAr: "سوفا",
    iso2: "fj",
  },
  {
    id: "finland",
    numericId: 61,
    nameEn: "Finland",
    nameAr: "فنلندا",
    flag: "🇫🇮",
    region: "Europe",
    capitalEn: "Helsinki",
    capitalAr: "هلسنكي",
    iso2: "fi",
  },
  {
    id: "france",
    numericId: 62,
    nameEn: "France",
    nameAr: "فرنسا",
    flag: "🇫🇷",
    region: "Europe",
    capitalEn: "Paris",
    capitalAr: "باريس",
    iso2: "fr",
  },
  {
    id: "gabon",
    numericId: 63,
    nameEn: "Gabon",
    nameAr: "الغابون",
    flag: "🇬🇦",
    region: "Africa",
    capitalEn: "Libreville",
    capitalAr: "ليبرفيل",
    iso2: "ga",
  },
  {
    id: "gambia",
    numericId: 64,
    nameEn: "Gambia",
    nameAr: "غامبيا",
    flag: "🇬🇲",
    region: "Africa",
    capitalEn: "Banjul",
    capitalAr: "بانجول",
    iso2: "gm",
  },
  {
    id: "georgia",
    numericId: 65,
    nameEn: "Georgia",
    nameAr: "جورجيا",
    flag: "🇬🇪",
    region: "Asia",
    capitalEn: "Tbilisi",
    capitalAr: "تبليسي",
    iso2: "ge",
  },
  {
    id: "germany",
    numericId: 66,
    nameEn: "Germany",
    nameAr: "ألمانيا",
    flag: "🇩🇪",
    region: "Europe",
    capitalEn: "Berlin",
    capitalAr: "برلين",
    iso2: "de",
  },
  {
    id: "ghana",
    numericId: 67,
    nameEn: "Ghana",
    nameAr: "غانا",
    flag: "🇬🇭",
    region: "Africa",
    capitalEn: "Accra",
    capitalAr: "أكرا",
    iso2: "gh",
  },
  {
    id: "greece",
    numericId: 68,
    nameEn: "Greece",
    nameAr: "اليونان",
    flag: "🇬🇷",
    region: "Europe",
    capitalEn: "Athens",
    capitalAr: "أثينا",
    iso2: "gr",
  },
  {
    id: "grenada",
    numericId: 69,
    nameEn: "Grenada",
    nameAr: "غرينادا",
    flag: "🇬🇩",
    region: "Americas",
    capitalEn: "Saint George's",
    capitalAr: "سانت جورج",
    iso2: "gd",
  },
  {
    id: "guatemala",
    numericId: 70,
    nameEn: "Guatemala",
    nameAr: "غواتيمالا",
    flag: "🇬🇹",
    region: "Americas",
    capitalEn: "Guatemala City",
    capitalAr: "غواتيمالا",
    iso2: "gt",
  },
  {
    id: "guinea",
    numericId: 71,
    nameEn: "Guinea",
    nameAr: "غينيا",
    flag: "🇬🇳",
    region: "Africa",
    capitalEn: "Conakry",
    capitalAr: "كوناكري",
    iso2: "gn",
  },
  {
    id: "guinea-bissau",
    numericId: 72,
    nameEn: "Guinea-Bissau",
    nameAr: "غينيا بيساو",
    flag: "🇬🇼",
    region: "Africa",
    capitalEn: "Bissau",
    capitalAr: "بيساو",
    iso2: "gw",
  },
  {
    id: "guyana",
    numericId: 73,
    nameEn: "Guyana",
    nameAr: "غيانا",
    flag: "🇬🇾",
    region: "Americas",
    capitalEn: "Georgetown",
    capitalAr: "جورجتاون",
    iso2: "gy",
  },
  {
    id: "haiti",
    numericId: 74,
    nameEn: "Haiti",
    nameAr: "هايتي",
    flag: "🇭🇹",
    region: "Americas",
    capitalEn: "Port-au-Prince",
    capitalAr: "بورت أو برنس",
    iso2: "ht",
  },
  {
    id: "honduras",
    numericId: 75,
    nameEn: "Honduras",
    nameAr: "هندوراس",
    flag: "🇭🇳",
    region: "Americas",
    capitalEn: "Tegucigalpa",
    capitalAr: "تيغوسيغالبا",
    iso2: "hn",
  },
  {
    id: "hungary",
    numericId: 76,
    nameEn: "Hungary",
    nameAr: "المجر",
    flag: "🇭🇺",
    region: "Europe",
    capitalEn: "Budapest",
    capitalAr: "بودابست",
    iso2: "hu",
  },
  {
    id: "iceland",
    numericId: 77,
    nameEn: "Iceland",
    nameAr: "آيسلندا",
    flag: "🇮🇸",
    region: "Europe",
    capitalEn: "Reykjavik",
    capitalAr: "ريكيافيك",
    iso2: "is",
  },
  {
    id: "india",
    numericId: 78,
    nameEn: "India",
    nameAr: "الهند",
    flag: "🇮🇳",
    region: "Asia",
    capitalEn: "New Delhi",
    capitalAr: "نيودلهي",
    iso2: "in",
  },
  {
    id: "indonesia",
    numericId: 79,
    nameEn: "Indonesia",
    nameAr: "إندونيسيا",
    flag: "🇮🇩",
    region: "Asia",
    capitalEn: "Jakarta",
    capitalAr: "جاكرتا",
    iso2: "id",
  },
  {
    id: "iran",
    numericId: 80,
    nameEn: "Iran",
    nameAr: "إيران",
    flag: "🇮🇷",
    region: "Middle East",
    capitalEn: "Tehran",
    capitalAr: "طهران",
    iso2: "ir",
  },
  {
    id: "iraq",
    numericId: 81,
    nameEn: "Iraq",
    nameAr: "العراق",
    flag: "🇮🇶",
    region: "Middle East",
    capitalEn: "Baghdad",
    capitalAr: "بغداد",
    iso2: "iq",
  },
  {
    id: "ireland",
    numericId: 82,
    nameEn: "Ireland",
    nameAr: "أيرلندا",
    flag: "🇮🇪",
    region: "Europe",
    capitalEn: "Dublin",
    capitalAr: "دبلن",
    iso2: "ie",
  },
  {
    id: "israel",
    numericId: 83,
    nameEn: "Israel",
    nameAr: "إسرائيل",
    flag: "🇮🇱",
    region: "Middle East",
    capitalEn: "Jerusalem",
    capitalAr: "القدس",
    iso2: "il",
  },
  {
    id: "italy",
    numericId: 84,
    nameEn: "Italy",
    nameAr: "إيطاليا",
    flag: "🇮🇹",
    region: "Europe",
    capitalEn: "Rome",
    capitalAr: "روما",
    iso2: "it",
  },
  {
    id: "jamaica",
    numericId: 85,
    nameEn: "Jamaica",
    nameAr: "جامايكا",
    flag: "🇯🇲",
    region: "Americas",
    capitalEn: "Kingston",
    capitalAr: "كينغستون",
    iso2: "jm",
  },
  {
    id: "japan",
    numericId: 86,
    nameEn: "Japan",
    nameAr: "اليابان",
    flag: "🇯🇵",
    region: "Asia",
    capitalEn: "Tokyo",
    capitalAr: "طوكيو",
    iso2: "jp",
  },
  {
    id: "jordan",
    numericId: 87,
    nameEn: "Jordan",
    nameAr: "الأردن",
    flag: "🇯🇴",
    region: "Middle East",
    capitalEn: "Amman",
    capitalAr: "عمّان",
    iso2: "jo",
  },
  {
    id: "kazakhstan",
    numericId: 88,
    nameEn: "Kazakhstan",
    nameAr: "كازاخستان",
    flag: "🇰🇿",
    region: "Asia",
    capitalEn: "Astana",
    capitalAr: "أستانا",
    iso2: "kz",
  },
  {
    id: "kenya",
    numericId: 89,
    nameEn: "Kenya",
    nameAr: "كينيا",
    flag: "🇰🇪",
    region: "Africa",
    capitalEn: "Nairobi",
    capitalAr: "نيروبي",
    iso2: "ke",
  },
  {
    id: "kiribati",
    numericId: 90,
    nameEn: "Kiribati",
    nameAr: "كيريباتي",
    flag: "🇰🇮",
    region: "Oceania",
    capitalEn: "Tarawa",
    capitalAr: "تاراوا",
    iso2: "ki",
  },
  {
    id: "kuwait",
    numericId: 91,
    nameEn: "Kuwait",
    nameAr: "الكويت",
    flag: "🇰🇼",
    region: "Middle East",
    capitalEn: "Kuwait City",
    capitalAr: "مدينة الكويت",
    iso2: "kw",
  },
  {
    id: "kyrgyzstan",
    numericId: 92,
    nameEn: "Kyrgyzstan",
    nameAr: "قيرغيزستان",
    flag: "🇰🇬",
    region: "Asia",
    capitalEn: "Bishkek",
    capitalAr: "بيشكك",
    iso2: "kg",
  },
  {
    id: "laos",
    numericId: 93,
    nameEn: "Laos",
    nameAr: "لاوس",
    flag: "🇱🇦",
    region: "Asia",
    capitalEn: "Vientiane",
    capitalAr: "فيينتيان",
    iso2: "la",
  },
  {
    id: "latvia",
    numericId: 94,
    nameEn: "Latvia",
    nameAr: "لاتفيا",
    flag: "🇱🇻",
    region: "Europe",
    capitalEn: "Riga",
    capitalAr: "ريغا",
    iso2: "lv",
  },
  {
    id: "lebanon",
    numericId: 95,
    nameEn: "Lebanon",
    nameAr: "لبنان",
    flag: "🇱🇧",
    region: "Middle East",
    capitalEn: "Beirut",
    capitalAr: "بيروت",
    iso2: "lb",
  },
  {
    id: "lesotho",
    numericId: 96,
    nameEn: "Lesotho",
    nameAr: "ليسوتو",
    flag: "🇱🇸",
    region: "Africa",
    capitalEn: "Maseru",
    capitalAr: "ماسيرو",
    iso2: "ls",
  },
  {
    id: "liberia",
    numericId: 97,
    nameEn: "Liberia",
    nameAr: "ليبيريا",
    flag: "🇱🇷",
    region: "Africa",
    capitalEn: "Monrovia",
    capitalAr: "مونروفيا",
    iso2: "lr",
  },
  {
    id: "libya",
    numericId: 98,
    nameEn: "Libya",
    nameAr: "ليبيا",
    flag: "🇱🇾",
    region: "Africa",
    capitalEn: "Tripoli",
    capitalAr: "طرابلس",
    iso2: "ly",
  },
  {
    id: "liechtenstein",
    numericId: 99,
    nameEn: "Liechtenstein",
    nameAr: "ليختنشتاين",
    flag: "🇱🇮",
    region: "Europe",
    capitalEn: "Vaduz",
    capitalAr: "فادوز",
    iso2: "li",
  },
  {
    id: "lithuania",
    numericId: 100,
    nameEn: "Lithuania",
    nameAr: "ليتوانيا",
    flag: "🇱🇹",
    region: "Europe",
    capitalEn: "Vilnius",
    capitalAr: "فيلنيوس",
    iso2: "lt",
  },
  {
    id: "luxembourg",
    numericId: 101,
    nameEn: "Luxembourg",
    nameAr: "لوكسمبورغ",
    flag: "🇱🇺",
    region: "Europe",
    capitalEn: "Luxembourg",
    capitalAr: "لوكسمبورغ",
    iso2: "lu",
  },
  {
    id: "madagascar",
    numericId: 102,
    nameEn: "Madagascar",
    nameAr: "مدغشقر",
    flag: "🇲🇬",
    region: "Africa",
    capitalEn: "Antananarivo",
    capitalAr: "أنتاناناريفو",
    iso2: "mg",
  },
  {
    id: "malawi",
    numericId: 103,
    nameEn: "Malawi",
    nameAr: "مالاوي",
    flag: "🇲🇼",
    region: "Africa",
    capitalEn: "Lilongwe",
    capitalAr: "ليلونغوي",
    iso2: "mw",
  },
  {
    id: "malaysia",
    numericId: 104,
    nameEn: "Malaysia",
    nameAr: "ماليزيا",
    flag: "🇲🇾",
    region: "Asia",
    capitalEn: "Kuala Lumpur",
    capitalAr: "كوالالمبور",
    iso2: "my",
  },
  {
    id: "maldives",
    numericId: 105,
    nameEn: "Maldives",
    nameAr: "جزر المالديف",
    flag: "🇲🇻",
    region: "Asia",
    capitalEn: "Malé",
    capitalAr: "ماليه",
    iso2: "mv",
  },
  {
    id: "mali",
    numericId: 106,
    nameEn: "Mali",
    nameAr: "مالي",
    flag: "🇲🇱",
    region: "Africa",
    capitalEn: "Bamako",
    capitalAr: "باماكو",
    iso2: "ml",
  },
  {
    id: "malta",
    numericId: 107,
    nameEn: "Malta",
    nameAr: "مالطا",
    flag: "🇲🇹",
    region: "Europe",
    capitalEn: "Valletta",
    capitalAr: "فاليتا",
    iso2: "mt",
  },
  {
    id: "marshall-islands",
    numericId: 108,
    nameEn: "Marshall Islands",
    nameAr: "جزر مارشال",
    flag: "🇲🇭",
    region: "Oceania",
    capitalEn: "Majuro",
    capitalAr: "ماجورو",
    iso2: "mh",
  },
  {
    id: "mauritania",
    numericId: 109,
    nameEn: "Mauritania",
    nameAr: "موريتانيا",
    flag: "🇲🇷",
    region: "Africa",
    capitalEn: "Nouakchott",
    capitalAr: "نواكشوط",
    iso2: "mr",
  },
  {
    id: "mauritius",
    numericId: 110,
    nameEn: "Mauritius",
    nameAr: "موريشيوس",
    flag: "🇲🇺",
    region: "Africa",
    capitalEn: "Port Louis",
    capitalAr: "بورت لويس",
    iso2: "mu",
  },
  {
    id: "mexico",
    numericId: 111,
    nameEn: "Mexico",
    nameAr: "المكسيك",
    flag: "🇲🇽",
    region: "Americas",
    capitalEn: "Mexico City",
    capitalAr: "مكسيكو سيتي",
    iso2: "mx",
  },
  {
    id: "micronesia",
    numericId: 112,
    nameEn: "Micronesia",
    nameAr: "ميكرونيزيا",
    flag: "🇫🇲",
    region: "Oceania",
    capitalEn: "Palikir",
    capitalAr: "باليكير",
    iso2: "fm",
  },
  {
    id: "moldova",
    numericId: 113,
    nameEn: "Moldova",
    nameAr: "مولدوفا",
    flag: "🇲🇩",
    region: "Europe",
    capitalEn: "Chișinău",
    capitalAr: "كيشيناو",
    iso2: "md",
  },
  {
    id: "monaco",
    numericId: 114,
    nameEn: "Monaco",
    nameAr: "موناكو",
    flag: "🇲🇨",
    region: "Europe",
    capitalEn: "Monaco",
    capitalAr: "موناكو",
    iso2: "mc",
  },
  {
    id: "mongolia",
    numericId: 115,
    nameEn: "Mongolia",
    nameAr: "منغوليا",
    flag: "🇲🇳",
    region: "Asia",
    capitalEn: "Ulaanbaatar",
    capitalAr: "أولان باتور",
    iso2: "mn",
  },
  {
    id: "montenegro",
    numericId: 116,
    nameEn: "Montenegro",
    nameAr: "الجبل الأسود",
    flag: "🇲🇪",
    region: "Europe",
    capitalEn: "Podgorica",
    capitalAr: "بودغوريتسا",
    iso2: "me",
  },
  {
    id: "morocco",
    numericId: 117,
    nameEn: "Morocco",
    nameAr: "المغرب",
    flag: "🇲🇦",
    region: "Africa",
    capitalEn: "Rabat",
    capitalAr: "الرباط",
    iso2: "ma",
  },
  {
    id: "mozambique",
    numericId: 118,
    nameEn: "Mozambique",
    nameAr: "موزمبيق",
    flag: "🇲🇿",
    region: "Africa",
    capitalEn: "Maputo",
    capitalAr: "مابوتو",
    iso2: "mz",
  },
  {
    id: "myanmar",
    numericId: 119,
    nameEn: "Myanmar",
    nameAr: "ميانمار",
    flag: "🇲🇲",
    region: "Asia",
    capitalEn: "Naypyidaw",
    capitalAr: "نايبيداو",
    iso2: "mm",
  },
  {
    id: "namibia",
    numericId: 120,
    nameEn: "Namibia",
    nameAr: "ناميبيا",
    flag: "🇳🇦",
    region: "Africa",
    capitalEn: "Windhoek",
    capitalAr: "ويندهوك",
    iso2: "na",
  },
  {
    id: "nauru",
    numericId: 121,
    nameEn: "Nauru",
    nameAr: "ناورو",
    flag: "🇳🇷",
    region: "Oceania",
    capitalEn: "Yaren",
    capitalAr: "يارين",
    iso2: "nr",
  },
  {
    id: "nepal",
    numericId: 122,
    nameEn: "Nepal",
    nameAr: "نيبال",
    flag: "🇳🇵",
    region: "Asia",
    capitalEn: "Kathmandu",
    capitalAr: "كاتماندو",
    iso2: "np",
  },
  {
    id: "netherlands",
    numericId: 123,
    nameEn: "Netherlands",
    nameAr: "هولندا",
    flag: "🇳🇱",
    region: "Europe",
    capitalEn: "Amsterdam",
    capitalAr: "أمستردام",
    iso2: "nl",
  },
  {
    id: "new-zealand",
    numericId: 124,
    nameEn: "New Zealand",
    nameAr: "نيوزيلندا",
    flag: "🇳🇿",
    region: "Oceania",
    capitalEn: "Wellington",
    capitalAr: "ويلينغتون",
    iso2: "nz",
  },
  {
    id: "nicaragua",
    numericId: 125,
    nameEn: "Nicaragua",
    nameAr: "نيكاراغوا",
    flag: "🇳🇮",
    region: "Americas",
    capitalEn: "Managua",
    capitalAr: "ماناغوا",
    iso2: "ni",
  },
  {
    id: "niger",
    numericId: 126,
    nameEn: "Niger",
    nameAr: "النيجر",
    flag: "🇳🇪",
    region: "Africa",
    capitalEn: "Niamey",
    capitalAr: "نيامي",
    iso2: "ne",
  },
  {
    id: "nigeria",
    numericId: 127,
    nameEn: "Nigeria",
    nameAr: "نيجيريا",
    flag: "🇳🇬",
    region: "Africa",
    capitalEn: "Abuja",
    capitalAr: "أبوجا",
    iso2: "ng",
  },
  {
    id: "north-korea",
    numericId: 128,
    nameEn: "North Korea",
    nameAr: "كوريا الشمالية",
    flag: "🇰🇵",
    region: "Asia",
    capitalEn: "Pyongyang",
    capitalAr: "بيونغ يانغ",
    iso2: "kp",
  },
  {
    id: "north-macedonia",
    numericId: 129,
    nameEn: "North Macedonia",
    nameAr: "مقدونيا الشمالية",
    flag: "🇲🇰",
    region: "Europe",
    capitalEn: "Skopje",
    capitalAr: "سكوبيه",
    iso2: "mk",
  },
  {
    id: "norway",
    numericId: 130,
    nameEn: "Norway",
    nameAr: "النرويج",
    flag: "🇳🇴",
    region: "Europe",
    capitalEn: "Oslo",
    capitalAr: "أوسلو",
    iso2: "no",
  },
  {
    id: "oman",
    numericId: 131,
    nameEn: "Oman",
    nameAr: "عُمان",
    flag: "🇴🇲",
    region: "Middle East",
    capitalEn: "Muscat",
    capitalAr: "مسقط",
    iso2: "om",
  },
  {
    id: "pakistan",
    numericId: 132,
    nameEn: "Pakistan",
    nameAr: "باكستان",
    flag: "🇵🇰",
    region: "Asia",
    capitalEn: "Islamabad",
    capitalAr: "إسلام آباد",
    iso2: "pk",
  },
  {
    id: "palau",
    numericId: 133,
    nameEn: "Palau",
    nameAr: "بالاو",
    flag: "🇵🇼",
    region: "Oceania",
    capitalEn: "Ngerulmud",
    capitalAr: "نغيرولمود",
    iso2: "pw",
  },
  {
    id: "panama",
    numericId: 134,
    nameEn: "Panama",
    nameAr: "بنما",
    flag: "🇵🇦",
    region: "Americas",
    capitalEn: "Panama City",
    capitalAr: "مدينة بنما",
    iso2: "pa",
  },
  {
    id: "papua-new-guinea",
    numericId: 135,
    nameEn: "Papua New Guinea",
    nameAr: "بابوا غينيا الجديدة",
    flag: "🇵🇬",
    region: "Oceania",
    capitalEn: "Port Moresby",
    capitalAr: "بورت مورسبي",
    iso2: "pg",
  },
  {
    id: "paraguay",
    numericId: 136,
    nameEn: "Paraguay",
    nameAr: "باراغواي",
    flag: "🇵🇾",
    region: "Americas",
    capitalEn: "Asunción",
    capitalAr: "أسونسيون",
    iso2: "py",
  },
  {
    id: "peru",
    numericId: 137,
    nameEn: "Peru",
    nameAr: "بيرو",
    flag: "🇵🇪",
    region: "Americas",
    capitalEn: "Lima",
    capitalAr: "ليما",
    iso2: "pe",
  },
  {
    id: "philippines",
    numericId: 138,
    nameEn: "Philippines",
    nameAr: "الفلبين",
    flag: "🇵🇭",
    region: "Asia",
    capitalEn: "Manila",
    capitalAr: "مانيلا",
    iso2: "ph",
  },
  {
    id: "poland",
    numericId: 139,
    nameEn: "Poland",
    nameAr: "بولندا",
    flag: "🇵🇱",
    region: "Europe",
    capitalEn: "Warsaw",
    capitalAr: "وارسو",
    iso2: "pl",
  },
  {
    id: "portugal",
    numericId: 140,
    nameEn: "Portugal",
    nameAr: "البرتغال",
    flag: "🇵🇹",
    region: "Europe",
    capitalEn: "Lisbon",
    capitalAr: "لشبونة",
    iso2: "pt",
  },
  {
    id: "qatar",
    numericId: 141,
    nameEn: "Qatar",
    nameAr: "قطر",
    flag: "🇶🇦",
    region: "Middle East",
    capitalEn: "Doha",
    capitalAr: "الدوحة",
    iso2: "qa",
  },
  {
    id: "romania",
    numericId: 142,
    nameEn: "Romania",
    nameAr: "رومانيا",
    flag: "🇷🇴",
    region: "Europe",
    capitalEn: "Bucharest",
    capitalAr: "بوخارست",
    iso2: "ro",
  },
  {
    id: "russia",
    numericId: 143,
    nameEn: "Russia",
    nameAr: "روسيا",
    flag: "🇷🇺",
    region: "Europe",
    capitalEn: "Moscow",
    capitalAr: "موسكو",
    iso2: "ru",
  },
  {
    id: "rwanda",
    numericId: 144,
    nameEn: "Rwanda",
    nameAr: "رواندا",
    flag: "🇷🇼",
    region: "Africa",
    capitalEn: "Kigali",
    capitalAr: "كيغالي",
    iso2: "rw",
  },
  {
    id: "saint-kitts-and-nevis",
    numericId: 145,
    nameEn: "Saint Kitts and Nevis",
    nameAr: "سانت كيتس ونيفيس",
    flag: "🇰🇳",
    region: "Americas",
    capitalEn: "Basseterre",
    capitalAr: "باستير",
    iso2: "kn",
  },
  {
    id: "saint-lucia",
    numericId: 146,
    nameEn: "Saint Lucia",
    nameAr: "سانت لوسيا",
    flag: "🇱🇨",
    region: "Americas",
    capitalEn: "Castries",
    capitalAr: "كاستريس",
    iso2: "lc",
  },
  {
    id: "saint-vincent-and-the-grenadines",
    numericId: 147,
    nameEn: "Saint Vincent and the Grenadines",
    nameAr: "سانت فنسنت والغرينادين",
    flag: "🇻🇨",
    region: "Americas",
    capitalEn: "Kingstown",
    capitalAr: "كينغستاون",
    iso2: "vc",
  },
  {
    id: "samoa",
    numericId: 148,
    nameEn: "Samoa",
    nameAr: "ساموا",
    flag: "🇼🇸",
    region: "Oceania",
    capitalEn: "Apia",
    capitalAr: "أبيا",
    iso2: "ws",
  },
  {
    id: "san-marino",
    numericId: 149,
    nameEn: "San Marino",
    nameAr: "سان مارينو",
    flag: "🇸🇲",
    region: "Europe",
    capitalEn: "San Marino",
    capitalAr: "سان مارينو",
    iso2: "sm",
  },
  {
    id: "sao-tome-and-principe",
    numericId: 150,
    nameEn: "São Tomé and Príncipe",
    nameAr: "ساو تومي وبرينسيب",
    flag: "🇸🇹",
    region: "Africa",
    capitalEn: "São Tomé",
    capitalAr: "ساو تومي",
    iso2: "st",
  },
  {
    id: "saudi-arabia",
    numericId: 151,
    nameEn: "Saudi Arabia",
    nameAr: "المملكة العربية السعودية",
    flag: "🇸🇦",
    region: "Middle East",
    capitalEn: "Riyadh",
    capitalAr: "الرياض",
    iso2: "sa",
  },
  {
    id: "senegal",
    numericId: 152,
    nameEn: "Senegal",
    nameAr: "السنغال",
    flag: "🇸🇳",
    region: "Africa",
    capitalEn: "Dakar",
    capitalAr: "داكار",
    iso2: "sn",
  },
  {
    id: "serbia",
    numericId: 153,
    nameEn: "Serbia",
    nameAr: "صربيا",
    flag: "🇷🇸",
    region: "Europe",
    capitalEn: "Belgrade",
    capitalAr: "بلغراد",
    iso2: "rs",
  },
  {
    id: "seychelles",
    numericId: 154,
    nameEn: "Seychelles",
    nameAr: "سيشل",
    flag: "🇸🇨",
    region: "Africa",
    capitalEn: "Victoria",
    capitalAr: "فيكتوريا",
    iso2: "sc",
  },
  {
    id: "sierra-leone",
    numericId: 155,
    nameEn: "Sierra Leone",
    nameAr: "سيراليون",
    flag: "🇸🇱",
    region: "Africa",
    capitalEn: "Freetown",
    capitalAr: "فريتاون",
    iso2: "sl",
  },
  {
    id: "singapore",
    numericId: 156,
    nameEn: "Singapore",
    nameAr: "سنغافورة",
    flag: "🇸🇬",
    region: "Asia",
    capitalEn: "Singapore",
    capitalAr: "سنغافورة",
    iso2: "sg",
  },
  {
    id: "slovakia",
    numericId: 157,
    nameEn: "Slovakia",
    nameAr: "سلوفاكيا",
    flag: "🇸🇰",
    region: "Europe",
    capitalEn: "Bratislava",
    capitalAr: "براتيسلافا",
    iso2: "sk",
  },
  {
    id: "slovenia",
    numericId: 158,
    nameEn: "Slovenia",
    nameAr: "سلوفينيا",
    flag: "🇸🇮",
    region: "Europe",
    capitalEn: "Ljubljana",
    capitalAr: "ليوبليانا",
    iso2: "si",
  },
  {
    id: "solomon-islands",
    numericId: 159,
    nameEn: "Solomon Islands",
    nameAr: "جزر سليمان",
    flag: "🇸🇧",
    region: "Oceania",
    capitalEn: "Honiara",
    capitalAr: "هونيارا",
    iso2: "sb",
  },
  {
    id: "somalia",
    numericId: 160,
    nameEn: "Somalia",
    nameAr: "الصومال",
    flag: "🇸🇴",
    region: "Africa",
    capitalEn: "Mogadishu",
    capitalAr: "مقديشو",
    iso2: "so",
  },
  {
    id: "south-africa",
    numericId: 161,
    nameEn: "South Africa",
    nameAr: "جنوب أفريقيا",
    flag: "🇿🇦",
    region: "Africa",
    capitalEn: "Pretoria",
    capitalAr: "بريتوريا",
    iso2: "za",
  },
  {
    id: "south-sudan",
    numericId: 162,
    nameEn: "South Sudan",
    nameAr: "جنوب السودان",
    flag: "🇸🇸",
    region: "Africa",
    capitalEn: "Juba",
    capitalAr: "جوبا",
    iso2: "ss",
  },
  {
    id: "spain",
    numericId: 163,
    nameEn: "Spain",
    nameAr: "إسبانيا",
    flag: "🇪🇸",
    region: "Europe",
    capitalEn: "Madrid",
    capitalAr: "مدريد",
    iso2: "es",
  },
  {
    id: "sri-lanka",
    numericId: 164,
    nameEn: "Sri Lanka",
    nameAr: "سريلانكا",
    flag: "🇱🇰",
    region: "Asia",
    capitalEn: "Sri Jayawardenepura Kotte",
    capitalAr: "سري جاياواردنابورا كوتي",
    iso2: "lk",
  },
  {
    id: "sudan",
    numericId: 165,
    nameEn: "Sudan",
    nameAr: "السودان",
    flag: "🇸🇩",
    region: "Africa",
    capitalEn: "Khartoum",
    capitalAr: "الخرطوم",
    iso2: "sd",
  },
  {
    id: "suriname",
    numericId: 166,
    nameEn: "Suriname",
    nameAr: "سورينام",
    flag: "🇸🇷",
    region: "Americas",
    capitalEn: "Paramaribo",
    capitalAr: "باراماريبو",
    iso2: "sr",
  },
  {
    id: "sweden",
    numericId: 167,
    nameEn: "Sweden",
    nameAr: "السويد",
    flag: "🇸🇪",
    region: "Europe",
    capitalEn: "Stockholm",
    capitalAr: "ستوكهولم",
    iso2: "se",
  },
  {
    id: "switzerland",
    numericId: 168,
    nameEn: "Switzerland",
    nameAr: "سويسرا",
    flag: "🇨🇭",
    region: "Europe",
    capitalEn: "Bern",
    capitalAr: "برن",
    iso2: "ch",
  },
  {
    id: "syria",
    numericId: 169,
    nameEn: "Syria",
    nameAr: "سوريا",
    flag: "🇸🇾",
    region: "Middle East",
    capitalEn: "Damascus",
    capitalAr: "دمشق",
    iso2: "sy",
  },
  {
    id: "tajikistan",
    numericId: 170,
    nameEn: "Tajikistan",
    nameAr: "طاجيكستان",
    flag: "🇹🇯",
    region: "Asia",
    capitalEn: "Dushanbe",
    capitalAr: "دوشانبي",
    iso2: "tj",
  },
  {
    id: "tanzania",
    numericId: 171,
    nameEn: "Tanzania",
    nameAr: "تنزانيا",
    flag: "🇹🇿",
    region: "Africa",
    capitalEn: "Dodoma",
    capitalAr: "دودوما",
    iso2: "tz",
  },
  {
    id: "thailand",
    numericId: 172,
    nameEn: "Thailand",
    nameAr: "تايلاند",
    flag: "🇹🇭",
    region: "Asia",
    capitalEn: "Bangkok",
    capitalAr: "بانكوك",
    iso2: "th",
  },
  {
    id: "timor-leste",
    numericId: 173,
    nameEn: "Timor-Leste",
    nameAr: "تيمور الشرقية",
    flag: "🇹🇱",
    region: "Asia",
    capitalEn: "Dili",
    capitalAr: "ديلي",
    iso2: "tl",
  },
  {
    id: "togo",
    numericId: 174,
    nameEn: "Togo",
    nameAr: "توغو",
    flag: "🇹🇬",
    region: "Africa",
    capitalEn: "Lomé",
    capitalAr: "لومي",
    iso2: "tg",
  },
  {
    id: "tonga",
    numericId: 175,
    nameEn: "Tonga",
    nameAr: "تونغا",
    flag: "🇹🇴",
    region: "Oceania",
    capitalEn: "Nuku'alofa",
    capitalAr: "نوكو ألوفا",
    iso2: "to",
  },
  {
    id: "trinidad-and-tobago",
    numericId: 176,
    nameEn: "Trinidad and Tobago",
    nameAr: "ترينيداد وتوباغو",
    flag: "🇹🇹",
    region: "Americas",
    capitalEn: "Port of Spain",
    capitalAr: "بورت أوف سبين",
    iso2: "tt",
  },
  {
    id: "tunisia",
    numericId: 177,
    nameEn: "Tunisia",
    nameAr: "تونس",
    flag: "🇹🇳",
    region: "Africa",
    capitalEn: "Tunis",
    capitalAr: "تونس",
    iso2: "tn",
  },
  {
    id: "turkey",
    numericId: 178,
    nameEn: "Turkey",
    nameAr: "تركيا",
    flag: "🇹🇷",
    region: "Middle East",
    capitalEn: "Ankara",
    capitalAr: "أنقرة",
    iso2: "tr",
  },
  {
    id: "turkmenistan",
    numericId: 179,
    nameEn: "Turkmenistan",
    nameAr: "تركمانستان",
    flag: "🇹🇲",
    region: "Asia",
    capitalEn: "Ashgabat",
    capitalAr: "عشق آباد",
    iso2: "tm",
  },
  {
    id: "tuvalu",
    numericId: 180,
    nameEn: "Tuvalu",
    nameAr: "توفالو",
    flag: "🇹🇻",
    region: "Oceania",
    capitalEn: "Funafuti",
    capitalAr: "فونافوتي",
    iso2: "tv",
  },
  {
    id: "uganda",
    numericId: 181,
    nameEn: "Uganda",
    nameAr: "أوغندا",
    flag: "🇺🇬",
    region: "Africa",
    capitalEn: "Kampala",
    capitalAr: "كمبالا",
    iso2: "ug",
  },
  {
    id: "ukraine",
    numericId: 182,
    nameEn: "Ukraine",
    nameAr: "أوكرانيا",
    flag: "🇺🇦",
    region: "Europe",
    capitalEn: "Kyiv",
    capitalAr: "كييف",
    iso2: "ua",
  },
  {
    id: "united-arab-emirates",
    numericId: 183,
    nameEn: "United Arab Emirates",
    nameAr: "الإمارات العربية المتحدة",
    flag: "🇦🇪",
    region: "Middle East",
    capitalEn: "Abu Dhabi",
    capitalAr: "أبوظبي",
    iso2: "ae",
  },
  {
    id: "united-kingdom",
    numericId: 184,
    nameEn: "United Kingdom",
    nameAr: "المملكة المتحدة",
    flag: "🇬🇧",
    region: "Europe",
    capitalEn: "London",
    capitalAr: "لندن",
    iso2: "gb",
  },
  {
    id: "united-states",
    numericId: 185,
    nameEn: "United States",
    nameAr: "الولايات المتحدة",
    flag: "🇺🇸",
    region: "Americas",
    capitalEn: "Washington, D.C.",
    capitalAr: "واشنطن",
    iso2: "us",
  },
  {
    id: "uruguay",
    numericId: 186,
    nameEn: "Uruguay",
    nameAr: "أوروغواي",
    flag: "🇺🇾",
    region: "Americas",
    capitalEn: "Montevideo",
    capitalAr: "مونتيفيديو",
    iso2: "uy",
  },
  {
    id: "uzbekistan",
    numericId: 187,
    nameEn: "Uzbekistan",
    nameAr: "أوزبكستان",
    flag: "🇺🇿",
    region: "Asia",
    capitalEn: "Tashkent",
    capitalAr: "طشقند",
    iso2: "uz",
  },
  {
    id: "vanuatu",
    numericId: 188,
    nameEn: "Vanuatu",
    nameAr: "فانواتو",
    flag: "🇻🇺",
    region: "Oceania",
    capitalEn: "Port Vila",
    capitalAr: "بورت فيلا",
    iso2: "vu",
  },
  {
    id: "venezuela",
    numericId: 189,
    nameEn: "Venezuela",
    nameAr: "فنزويلا",
    flag: "🇻🇪",
    region: "Americas",
    capitalEn: "Caracas",
    capitalAr: "كاراكاس",
    iso2: "ve",
  },
  {
    id: "vietnam",
    numericId: 190,
    nameEn: "Vietnam",
    nameAr: "فيتنام",
    flag: "🇻🇳",
    region: "Asia",
    capitalEn: "Hanoi",
    capitalAr: "هانوي",
    iso2: "vn",
  },
  {
    id: "yemen",
    numericId: 191,
    nameEn: "Yemen",
    nameAr: "اليمن",
    flag: "🇾🇪",
    region: "Middle East",
    capitalEn: "Sanaa",
    capitalAr: "صنعاء",
    iso2: "ye",
  },
  {
    id: "zambia",
    numericId: 192,
    nameEn: "Zambia",
    nameAr: "زامبيا",
    flag: "🇿🇲",
    region: "Africa",
    capitalEn: "Lusaka",
    capitalAr: "لوساكا",
    iso2: "zm",
  },
  {
    id: "zimbabwe",
    numericId: 193,
    nameEn: "Zimbabwe",
    nameAr: "زيمبابوي",
    flag: "🇿🇼",
    region: "Africa",
    capitalEn: "Harare",
    capitalAr: "هراري",
    iso2: "zw",
  },
]

export function getCountryById(id: string): WorldCountry | undefined {
  return WORLD_COUNTRIES.find((c) => c.id === id || String(c.numericId) === id)
}
